<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="2" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="28283" started-at="2021-12-17T13:53:34Z" finished-at="2021-12-17T13:54:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="28283" started-at="2021-12-17T13:53:34Z" finished-at="2021-12-17T13:54:03Z">
      <class name="com.carbonite.qa.tests.SignUpPageTest">
        <test-method status="PASS" signature="loggersetUp()[pri:0, instance:com.carbonite.qa.tests.SignUpPageTest@78e117e3]" name="loggersetUp" is-config="true" duration-ms="111" started-at="2021-12-17T13:53:34Z" finished-at="2021-12-17T13:53:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loggersetUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.carbonite.qa.tests.SignUpPageTest@78e117e3]" name="setUp" is-config="true" duration-ms="9181" started-at="2021-12-17T13:53:36Z" finished-at="2021-12-17T13:53:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="fillSignUpFormWithValidTestData(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.carbonite.qa.tests.SignUpPageTest@78e117e3]" name="fillSignUpFormWithValidTestData" duration-ms="1518" started-at="2021-12-17T13:53:45Z" data-provider="PositiveSignUpDataFromExcelFile" finished-at="2021-12-17T13:53:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[manvir..singh9@it.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[manvir..singh9@it.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Manager@123]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Manager@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Download] but found [Try Carbonite Computer Backup Free For 15 Days | Carbonite]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Download] but found [Try Carbonite Computer Backup Free For 15 Days | Carbonite]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.carbonite.qa.tests.SignUpPageTest.fillSignUpFormWithValidTestData(SignUpPageTest.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fillSignUpFormWithValidTestData -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.carbonite.qa.tests.SignUpPageTest@78e117e3]" name="tearDown" is-config="true" duration-ms="927" started-at="2021-12-17T13:53:46Z" finished-at="2021-12-17T13:53:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.carbonite.qa.tests.SignUpPageTest@78e117e3]" name="setUp" is-config="true" duration-ms="6255" started-at="2021-12-17T13:53:47Z" finished-at="2021-12-17T13:53:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="fillSignUpFormWithValidTestData(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.carbonite.qa.tests.SignUpPageTest@78e117e3]" name="fillSignUpFormWithValidTestData" duration-ms="1166" started-at="2021-12-17T13:53:54Z" data-provider="PositiveSignUpDataFromExcelFile" finished-at="2021-12-17T13:53:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[manvir..singh91@it.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[manvir..singh91@it.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Manager@123]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Manager@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Download] but found [Try Carbonite Computer Backup Free For 15 Days | Carbonite]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Download] but found [Try Carbonite Computer Backup Free For 15 Days | Carbonite]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.carbonite.qa.tests.SignUpPageTest.fillSignUpFormWithValidTestData(SignUpPageTest.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fillSignUpFormWithValidTestData -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.carbonite.qa.tests.SignUpPageTest@78e117e3]" name="tearDown" is-config="true" duration-ms="742" started-at="2021-12-17T13:53:55Z" finished-at="2021-12-17T13:53:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.carbonite.qa.tests.SignUpPageTest@78e117e3]" name="setUp" is-config="true" duration-ms="5173" started-at="2021-12-17T13:53:56Z" finished-at="2021-12-17T13:54:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="fillSignUpFormWithValidTestData(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.carbonite.qa.tests.SignUpPageTest@78e117e3]" name="fillSignUpFormWithValidTestData" duration-ms="1071" started-at="2021-12-17T13:54:01Z" data-provider="PositiveSignUpDataFromExcelFile" finished-at="2021-12-17T13:54:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[manvir..singh92@it.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[manvir..singh92@it.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Manager@123]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Manager@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Download] but found [Try Carbonite Computer Backup Free For 15 Days | Carbonite]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Download] but found [Try Carbonite Computer Backup Free For 15 Days | Carbonite]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.carbonite.qa.tests.SignUpPageTest.fillSignUpFormWithValidTestData(SignUpPageTest.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fillSignUpFormWithValidTestData -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.carbonite.qa.tests.SignUpPageTest@78e117e3]" name="tearDown" is-config="true" duration-ms="889" started-at="2021-12-17T13:54:02Z" finished-at="2021-12-17T13:54:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.carbonite.qa.tests.SignUpPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
